mkdir ../assembly
mkdir ../cnv_analysis
mkdir ../coverage
mkdir ../duplicates
mkdir ../intervals
mkdir ../logs
mkdir ../metrics
mkdir ../raw_reads
mkdir ../results
mkdir ../summary
mkdir ../variants
mkdir ../variants/haplotyper
mkdir ../variants_6q24
mkdir ../variants_t1d
